import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
import sharp from 'sharp';

const base = process.env.LIVE_URL || 'http://127.0.0.1:4173/framepack/';
await fs.mkdir('qa/screenshots', { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const page = await context.newPage();
await page.addInitScript(() => { localStorage.setItem('framepack-lang', 'en'); localStorage.setItem('framepack-theme', 'light'); });
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base);
const checks=[];
async function record(name, opts={}) {
  await page.waitForTimeout(150);
  await page.screenshot({ path: `qa/screenshots/${name}.png`, fullPage: true });
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();
  const layout=await page.evaluate(() => ({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyScrollWidth:document.body.scrollWidth,lang:document.documentElement.lang,theme:document.documentElement.dataset.theme,recipeGeometry:['.recipe','.recipe fieldset','.width-options','.width-options button:last-child'].map(s=>({selector:s,width:document.querySelector(s)?.getBoundingClientRect().width,right:document.querySelector(s)?.getBoundingClientRect().right})),original:[...document.querySelectorAll('.preview-frame img')].map(e=>({naturalWidth:e.naturalWidth,naturalHeight:e.naturalHeight,renderWidth:e.getBoundingClientRect().width,renderHeight:e.getBoundingClientRect().height})),oversized:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1 && !e.closest('table,pre')).slice(0,25).map(e=>({tag:e.tagName,class:e.className,right:Math.round(e.getBoundingClientRect().right)}))}));
  checks.push({name,...opts,layout,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,help:v.help,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
}
await record('desktop-en-light-empty');
await page.keyboard.press('Tab');
checks.push({name:'keyboard-skip-link',focus:await page.evaluate(()=>({tag:document.activeElement?.tagName,text:document.activeElement?.textContent,visible:document.activeElement?.getBoundingClientRect().top>=0,outline:getComputedStyle(document.activeElement).outlineStyle}))});
await page.keyboard.press('Enter');
await page.keyboard.press('Tab');
checks.push({name:'keyboard-after-skip',focus:await page.evaluate(()=>({tag:document.activeElement?.tagName,text:document.activeElement?.textContent}))});
await page.getByRole('button',{name:/^320/}).focus();
await page.keyboard.press('Space');
checks.push({name:'keyboard-width-toggle',pressed:await page.getByRole('button',{name:/^320/}).getAttribute('aria-pressed')});
await page.keyboard.press('Space');
await page.getByRole('button',{name:'Try a demo',exact:true}).click();
await page.getByRole('button',{name:'Build assets',exact:true}).click();
await page.getByRole('button',{name:'Download ZIP'}).waitFor({state:'visible'});
await page.waitForFunction(()=>document.querySelectorAll('.status.complete').length===3);
await page.getByRole('button',{name:'Compare',exact:true}).first().focus();
await page.keyboard.press('Enter');
await page.waitForFunction(()=>document.activeElement?.id==='compare-title');
checks.push({name:'keyboard-compare-destination',focus:await page.evaluate(()=>({id:document.activeElement?.id,top:document.activeElement?.getBoundingClientRect().top,text:document.activeElement?.textContent}))});
await record('desktop-en-light-ready');
await page.getByRole('button',{name:'Color theme: Dark'}).click();
await record('desktop-en-dark-ready');
await page.getByLabel('Language',{exact:true}).selectOption('ru');
await record('desktop-ru-dark-ready');
await page.getByRole('button',{name:'Цветовая тема: Светлая'}).click();
await record('desktop-ru-light-ready');
await page.setViewportSize({width:320,height:740});
await record('mobile-320-ru-light-ready');
await page.getByRole('button',{name:'Цветовая тема: Тёмная'}).click();
await record('mobile-320-ru-dark-ready');
await page.getByLabel('Язык',{exact:true}).selectOption('en');
await record('mobile-320-en-dark-ready');
await page.getByRole('button',{name:'Color theme: Light'}).click();
await record('mobile-320-en-light-ready');
const table=page.locator('.variant-table');
await table.focus();
const scrollBefore=await table.evaluate(e=>e.scrollLeft);
await page.keyboard.press('ArrowRight');
await page.keyboard.press('ArrowRight');
await page.waitForTimeout(250);
checks.push({name:'keyboard-mobile-table-scroll',before:scrollBefore,after:await table.evaluate(e=>e.scrollLeft),focus:await table.evaluate(e=>({active:document.activeElement===e,outline:getComputedStyle(e).outlineStyle,label:e.getAttribute('aria-label')}))});
await page.screenshot({path:'qa/screenshots/keyboard-mobile-table-scroll.png',fullPage:true});
await page.getByRole('button',{name:'Color theme: Dark'}).click();
await page.setViewportSize({width:768,height:1024});
await page.evaluate(()=>document.documentElement.style.fontSize='200%');
await record('text-200-percent-768-en-dark-ready',{description:'Root font-size 200%, desktop/tablet reflow equivalent check; not browser zoom.'});
await page.evaluate(()=>document.documentElement.style.fontSize='');
await page.evaluate(()=>{const s=[...document.querySelectorAll('.app-shell *')].map(e=>[e,parseFloat(getComputedStyle(e).fontSize)]);for(const [e,n] of s)e.style.fontSize=`${n*2}px`;});
await record('all-text-200-percent-768-en-dark-ready',{description:'User text enlargement: all precomputed CSS font sizes doubled, including explicit px values; not browser zoom.'});
await page.setViewportSize({width:320,height:740});
await record('all-text-200-percent-320-en-dark-ready',{description:'Same complete text enlargement under narrow mobile reflow; font sizes initially computed at 768 px.'});
await page.locator('.topbar').screenshot({path:'qa/screenshots/text-200-mobile-header-detail.png'});
await page.locator('.recipe').screenshot({path:'qa/screenshots/text-200-mobile-recipe-detail.png'});
await page.locator('.queue').screenshot({path:'qa/screenshots/text-200-mobile-queue-detail.png'});
await page.setViewportSize({width:1440,height:1000});
await record('all-text-200-percent-1440-en-dark-ready',{description:'Same complete text enlargement under desktop layout; font sizes initially computed at 768 px.'});
await page.reload();
await page.getByRole('button',{name:'Try a demo',exact:true}).click();
await page.getByRole('button',{name:'Build assets',exact:true}).click();
await page.waitForFunction(()=>document.querySelectorAll('.status.complete').length===3);
await page.getByRole('button',{name:'Color theme: Dark'}).click();
await page.setViewportSize({width:1440,height:1000});
await page.getByRole('button',{name:'Clear queue',exact:true}).click();
await page.locator('input[type=file]').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('not an image')});
await page.getByRole('button',{name:'Build assets',exact:true}).click();
await page.locator('.status.error').waitFor();
await record('desktop-en-dark-error');
checks.push({name:'error-announcement',liveText:await page.locator('[role=status]').textContent(),errorAlert:await page.locator('.error-text').getAttribute('role')});
await page.getByRole('button',{name:'Clear queue',exact:true}).click();
await page.getByLabel('Format',{exact:true}).selectOption('png');
const largePng=await sharp({create:{width:3000,height:2000,channels:4,background:'#6449d8'}}).png().toBuffer();
await page.locator('input[type=file]').setInputFiles(Array.from({length:8},(_,i)=>({name:`audit-study-${i+1}.png`,mimeType:'image/png',buffer:largePng})));
await page.getByRole('button',{name:'Build assets',exact:true}).click();
await page.locator('.status.processing').first().waitFor();
await page.screenshot({path:'qa/screenshots/desktop-en-dark-processing.png',fullPage:true});
await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.getByRole('button',{name:'Build assets',exact:true}).waitFor();
await page.locator('.status.cancelled').first().waitFor();
await record('desktop-en-dark-cancelled');
checks.push({name:'cancel-announcement',liveText:await page.locator('[role=status]').textContent(),cancelled:await page.locator('.status.cancelled').count()});
await page.getByRole('button',{name:/Retry: audit-study-/}).first().click();
await page.waitForFunction(()=>document.querySelectorAll('.status.complete').length>=1);
await page.getByRole('button',{name:'Build assets',exact:true}).waitFor();
await record('desktop-en-dark-retried');
await page.getByRole('button',{name:'Build assets',exact:true}).click();
await page.waitForFunction(()=>document.querySelectorAll('.status.complete').length===8);
await record('desktop-en-dark-rerun-ready');
checks.push({name:'touch-targets',targets:await page.evaluate(()=>[...document.querySelectorAll('button,select,input,summary,a')].filter(e=>{const s=getComputedStyle(e),b=e.getBoundingClientRect();return s.visibility!=='hidden'&&s.display!=='none'&&b.width>2&&b.height>2}).map(e=>({tag:e.tagName,text:e.getAttribute('aria-label')||e.textContent?.trim().slice(0,70),width:Math.round(e.getBoundingClientRect().width),height:Math.round(e.getBoundingClientRect().height)})).filter(e=>e.width<24||e.height<24))});
const touchContext=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,deviceScaleFactor:2});
const touch=await touchContext.newPage();
await touch.addInitScript(()=>{localStorage.setItem('framepack-lang','en');localStorage.setItem('framepack-theme','light');});
await touch.goto(base);
await touch.getByRole('button',{name:/^320/}).tap();
const touchPressed=await touch.getByRole('button',{name:/^320/}).getAttribute('aria-pressed');
await touch.getByRole('button',{name:'Try a demo',exact:true}).tap();
await touch.getByRole('button',{name:'Build assets',exact:true}).tap();
await touch.waitForFunction(()=>document.querySelectorAll('.status.complete').length===3);
await touch.getByRole('button',{name:'Color theme: Dark'}).tap();
await touch.screenshot({path:'qa/screenshots/touch-375-en-dark-ready.png',fullPage:true});
const touchAxe=await new AxeBuilder({page:touch}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();
checks.push({name:'touch-emulation-375-demo-build-theme',pressed:touchPressed,ready:await touch.locator('.status.complete').count(),violations:touchAxe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
await touchContext.close();
await fs.writeFile('qa/design-a11y-results.json',JSON.stringify({base,time:new Date().toISOString(),browser:'Playwright Chromium',errors,checks},null,2));
await browser.close();
console.log(JSON.stringify({checks:checks.map(c=>({name:c.name,violations:c.violations?.map(v=>({id:v.id,impact:v.impact,count:v.nodes.length})),layout:c.layout?{width:c.layout.width,scrollWidth:c.layout.scrollWidth,original:c.layout.original,oversized:c.layout.oversized}:undefined,focus:c.focus,targets:c.targets})),errors},null,2));
